"""Input Processor error types."""

from enum import StrEnum


class InputProcessingErrorCode(StrEnum):
    """Controlled Input Processor failure categories."""

    INVALID_INPUT = "INVALID_INPUT"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    SIGNATURE_MISMATCH = "SIGNATURE_MISMATCH"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    TOO_MANY_ATTACHMENTS = "TOO_MANY_ATTACHMENTS"
    TOTAL_UPLOAD_TOO_LARGE = "TOTAL_UPLOAD_TOO_LARGE"
    PDF_PAGE_LIMIT_EXCEEDED = "PDF_PAGE_LIMIT_EXCEEDED"
    SPREADSHEET_WORKSHEET_LIMIT_EXCEEDED = "SPREADSHEET_WORKSHEET_LIMIT_EXCEEDED"
    UNSUPPORTED_WORKBOOK_PROTECTION = "UNSUPPORTED_WORKBOOK_PROTECTION"
    OCR_FAILURE = "OCR_FAILURE"
    EXTRACTION_FAILURE = "EXTRACTION_FAILURE"
    UNREADABLE_CONTENT = "UNREADABLE_CONTENT"
    PII_PROCESSING_FAILURE = "PII_PROCESSING_FAILURE"
    SAFETY_REJECTION = "SAFETY_REJECTION"
    INTERNAL_PROCESSING_ERROR = "INTERNAL_PROCESSING_ERROR"


class InputProcessingWarningCode(StrEnum):
    """Controlled Input Processor warning categories."""

    LOW_TEXT_CONTENT = "LOW_TEXT_CONTENT"
    SUSPICIOUS_INSTRUCTION = "SUSPICIOUS_INSTRUCTION"
    SPREADSHEET_ROW_LIMIT_APPLIED = "SPREADSHEET_ROW_LIMIT_APPLIED"
    SPREADSHEET_COLUMN_LIMIT_APPLIED = "SPREADSHEET_COLUMN_LIMIT_APPLIED"
    SPREADSHEET_CELL_TRUNCATED = "SPREADSHEET_CELL_TRUNCATED"
    SPREADSHEET_HIDDEN_CONTENT_EXCLUDED = "SPREADSHEET_HIDDEN_CONTENT_EXCLUDED"
    SPREADSHEET_CACHED_FORMULA_VALUE_UNAVAILABLE = (
        "SPREADSHEET_CACHED_FORMULA_VALUE_UNAVAILABLE"
    )
    SPREADSHEET_TABLE_METADATA_UNAVAILABLE = (
        "SPREADSHEET_TABLE_METADATA_UNAVAILABLE"
    )
    SPREADSHEET_PARTIAL_WORKSHEET_EXTRACTION = (
        "SPREADSHEET_PARTIAL_WORKSHEET_EXTRACTION"
    )


class InputProcessingError(Exception):
    """Base error for controlled Input Processor failures."""

    def __init__(self, code: InputProcessingErrorCode, message: str) -> None:
        if not message.strip():
            raise ValueError("message must not be empty")
        self.code = code
        self.message = message
        super().__init__(message)


__all__ = [
    "InputProcessingError",
    "InputProcessingErrorCode",
    "InputProcessingWarningCode",
]
